#!/bin/bash
# Script to aggregate ITA HWPE SystemVerilog files in the correct dependency order
# This ensures packages are compiled before they are used

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VSRC_DIR="${SCRIPT_DIR}/src/main/resources/vsrc"
OUTPUT_FILE="${VSRC_DIR}/hwpe/ita_hwpe_aggregated.sv"

# Create output file
> "${OUTPUT_FILE}"

echo "// Auto-generated aggregated file for ITA HWPE" >> "${OUTPUT_FILE}"
echo "// DO NOT EDIT - Generated by aggregate_hwpe_files.sh" >> "${OUTPUT_FILE}"
echo "// This file contains all necessary SystemVerilog files in dependency order" >> "${OUTPUT_FILE}"
echo "" >> "${OUTPUT_FILE}"

# Function to append file with header, removing include statements for files we've already included
append_file() {
    local file="$1"
    local desc="$2"
    if [ -f "${file}" ]; then
        echo "// ============================================================================" >> "${OUTPUT_FILE}"
        echo "// ${desc}" >> "${OUTPUT_FILE}"
        echo "// Source: ${file}" >> "${OUTPUT_FILE}"
        echo "// ============================================================================" >> "${OUTPUT_FILE}"
        # Remove include statements for files we've already aggregated
        # This prevents macro redefinition errors
        # Match any whitespace before `include and handle both single and double quotes
        sed -e '/[[:space:]]*`include[[:space:]]*"common_cells\/assertions.svh"/d' \
            -e '/[[:space:]]*`include[[:space:]]*"common_cells\/registers.svh"/d' \
            -e '/[[:space:]]*`include[[:space:]]*"hwpe_stream_package.sv"/d' \
            -e '/[[:space:]]*`include[[:space:]]*"hwpe_ctrl_package.sv"/d' \
            -e '/[[:space:]]*`include[[:space:]]*"hci_package.sv"/d' \
            -e '/[[:space:]]*`include[[:space:]]*"hci_helpers.svh"/d' \
            -e '/[[:space:]]*`include[[:space:]]*"ita_hwpe_package.sv"/d' \
            -e '/[[:space:]]*`include[[:space:]]*"ita_package.sv"/d' \
            -e '/[[:space:]]*`include[[:space:]]*"cf_math_pkg.sv"/d' \
            "${file}" >> "${OUTPUT_FILE}"
        echo "" >> "${OUTPUT_FILE}"
        echo "" >> "${OUTPUT_FILE}"
    else
        echo "Warning: File not found: ${file}" >&2
    fi
}

# Step 0: Add all Bender package files (excluding testbenches and deprecated)
echo "Adding Bender package files..."
BENDER_DIR="${SCRIPT_DIR}/.bender/git/checkouts"

# Function to append bender files, excluding testbenches and deprecated
append_bender_files() {
    local package_dir="$1"
    local desc="$2"
    if [ -d "${package_dir}" ]; then
        # Find all .sv, .svh, .v files, excluding testbench and deprecated directories
        local files=$(find "${package_dir}" -type f \( -name "*.sv" -o -name "*.svh" -o -name "*.v" \) \
            ! -path "*/TB/*" ! -path "*/tb/*" ! -path "*/test/*" ! -path "*/verif/*" \
            ! -path "*/deprecated/*" ! -path "*/formal/*" ! -path "*/sim/*" \
            | sort)
        
        if [ -n "${files}" ]; then
            echo "Processing ${desc}..."
            for file in ${files}; do
                local rel_path=$(echo "${file}" | sed "s|${package_dir}/||")
                echo "  Adding: ${rel_path}"
                append_file "${file}" "${desc} - ${rel_path}"
            done
        fi
    fi
}

# Add Bender packages in dependency order
# 1. common_cells (base utilities)
if [ -d "${BENDER_DIR}/cluster_interconnect-"* ]; then
    append_bender_files "${BENDER_DIR}/cluster_interconnect-"* "Cluster interconnect (Bender)"
fi

if [ -d "${BENDER_DIR}/common_cells-"* ]; then
    append_bender_files "${BENDER_DIR}/common_cells-"* "Common cells (Bender)"
fi

# 4. hci (HCI package)
if [ -d "${BENDER_DIR}/hci-"* ]; then
    append_bender_files "${BENDER_DIR}/hci-"* "HCI (Bender)"
fi

# 2. hwpe-stream (stream package)
if [ -d "${BENDER_DIR}/hwpe-stream-"* ]; then
    append_bender_files "${BENDER_DIR}/hwpe-stream-"* "HWPE stream (Bender)"
fi

# 3. hwpe-ctrl (control package)
if [ -d "${BENDER_DIR}/hwpe-ctrl-"* ]; then
    append_bender_files "${BENDER_DIR}/hwpe-ctrl-"* "HWPE ctrl (Bender)"
fi

# 5. Other Bender packages that might be needed
if [ -d "${BENDER_DIR}/scm-"* ]; then
    append_bender_files "${BENDER_DIR}/scm-"* "SCM (Bender)"
fi

if [ -d "${BENDER_DIR}/tech_cells_generic-"* ]; then
    append_bender_files "${BENDER_DIR}/tech_cells_generic-"* "Tech cells generic (Bender)"
fi

# Step 1: Base packages (no dependencies)
echo "Adding base packages..."
append_file "${VSRC_DIR}/cf_math_pkg.sv" "Base math package"
append_file "${VSRC_DIR}/ita_package.sv" "ITA package"

# Step 2: Common cells (needed by various modules)
echo "Adding common cells..."
append_file "${VSRC_DIR}/fifo_v3.sv" "FIFO common cell"
append_file "${VSRC_DIR}/tc_sram.sv" "SRAM common cell"
append_file "${VSRC_DIR}/lzc.sv" "Leading zero counter"
append_file "${VSRC_DIR}/cluster_clock_gating.sv" "Clock gating cell"

# Step 3: HWPE stream package (no dependencies on other hwpe packages)
echo "Adding hwpe_stream_package..."
append_file "${VSRC_DIR}/hwpe/hwpe_stream_package.sv" "HWPE stream package"

# Step 4: HWPE ctrl package (may depend on hwpe_stream)
echo "Adding hwpe_ctrl_package..."
append_file "${VSRC_DIR}/hwpe/hwpe_ctrl_package.sv" "HWPE control package"

# Step 5: HCI helpers (macros and interfaces)
echo "Adding hci_helpers..."
append_file "${VSRC_DIR}/hwpe/hci_helpers.svh" "HCI helper macros and interfaces"

# Step 6: HCI package (depends on hwpe_stream_package)
echo "Adding hci_package..."
echo "// ============================================================================" >> "${OUTPUT_FILE}"
echo "// HCI package (depends on hwpe_stream_package)" >> "${OUTPUT_FILE}"
echo "// Source: ${VSRC_DIR}/hwpe/hci_package.sv" >> "${OUTPUT_FILE}"
echo "// ============================================================================" >> "${OUTPUT_FILE}"
# Remove the include directive since hwpe_stream_package is already included above
sed '/^`include "hwpe_stream_package.sv"/d' "${VSRC_DIR}/hwpe/hci_package.sv" >> "${OUTPUT_FILE}"
echo "" >> "${OUTPUT_FILE}"
echo "" >> "${OUTPUT_FILE}"

# Step 7: ITA HWPE package (depends on hci_package and ita_package)
echo "Adding ita_hwpe_package..."
append_file "${VSRC_DIR}/hwpe/ita_hwpe_package.sv" "ITA HWPE package"

# Step 8: ITA HWPE modules (in dependency order)
echo "Adding ITA HWPE modules..."

# Function to append file without includes/imports
append_file_no_includes() {
    local file="$1"
    local desc="$2"
    if [ -f "${file}" ]; then
        echo "// ============================================================================" >> "${OUTPUT_FILE}"
        echo "// ${desc}" >> "${OUTPUT_FILE}"
        echo "// Source: ${file}" >> "${OUTPUT_FILE}"
        echo "// ============================================================================" >> "${OUTPUT_FILE}"
        # Remove include directives and import statements (they're already included above)
        # Also remove includes for files we've already aggregated
        sed -e '/^`include/d' \
            -e '/^import/d' \
            "${file}" >> "${OUTPUT_FILE}"
        echo "" >> "${OUTPUT_FILE}"
        echo "" >> "${OUTPUT_FILE}"
    else
        echo "Warning: File not found: ${file}" >&2
    fi
}

# Modules in dependency order (dependencies first)
append_file_no_includes "${VSRC_DIR}/hwpe/ita_hwpe_engine.sv" "ITA HWPE engine"
append_file_no_includes "${VSRC_DIR}/hwpe/ita_hwpe_input_buffer.sv" "ITA HWPE input buffer"
append_file_no_includes "${VSRC_DIR}/hwpe/ita_hwpe_input_bias_buffer.sv" "ITA HWPE input bias buffer"
append_file_no_includes "${VSRC_DIR}/hwpe/ita_hwpe_input_bias_fence.sv" "ITA HWPE input bias fence"
append_file_no_includes "${VSRC_DIR}/hwpe/ita_hwpe_output_buffer.sv" "ITA HWPE output buffer"
append_file_no_includes "${VSRC_DIR}/hwpe/ita_hwpe_ctrl.sv" "ITA HWPE controller"
append_file_no_includes "${VSRC_DIR}/hwpe/ita_hwpe_streamer.sv" "ITA HWPE streamer"
append_file_no_includes "${VSRC_DIR}/hwpe/ita_hwpe_top.sv" "ITA HWPE top module"
append_file_no_includes "${VSRC_DIR}/hwpe/ita_hwpe_wrap.sv" "ITA HWPE wrapper"

echo "Aggregation complete: ${OUTPUT_FILE}"
echo "Total lines: $(wc -l < "${OUTPUT_FILE}")"

